# Tasks for internal mlnx lab

- name: Get docker registry certificate from arc-build-server
  fetch:
    src: /docker/certs/domain.crt
    dest: /tmp/
    flat: true
  delegate_to: arc-build-server

- name: Create directory for certificate
  file:
    path: /etc/docker/certs.d/arc-build-server:5000
    state: directory
    mode: 0755


- name: Copy registry certificate to switch
  copy:
    src: /tmp/domain.crt
    dest: /etc/docker/certs.d/arc-build-server:5000/ca.crt

- name: Change onie platform version
  lineinfile:
    dest: /host/machine.conf
    regexp: '^onie_platform=x86_64-mlnx_x86-r5.0.1410'
    line: 'onie_platform=x86_64-mlnx_x86-r5.0.1400'

- name: Copy kernel MFT
  copy:
    src: /sonic/mlnx-sdk/kernel-mft-modules_4.1.0-34-3.16.0-4-amd64_all.deb
    dest: /tmp/kernel-mft-modules_4.1.0-34-3.16.0-4-amd64_all.deb

- name: Install kernel MFT
  apt:
    deb: /tmp/kernel-mft-modules_4.1.0-34-3.16.0-4-amd64_all.deb

