root_path: /images/veos-vm
#vm_images_url: https://acsbe.blob.core.windows.net/vmimages
cd_image_filename: Aboot-veos-8.0.0.iso
hdd_image_filename: vEOS-lab-4.16.6M.vmdk

# proxy
#proxy_env:
#  http_proxy: http://10.252.0.99:3128
#  https_proxy: http://10.252.0.99:3128

